name: My First Workflow

on: 
  push:
    branches: 
      -main
  workflow_dispatch:

  schedule:
    - cron: '0 15-17 10 */3 *'

jobs: 
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🤗 Hello World!"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in the repository
        run: |
          echo " The repository ${{github.respository}} contains the following files:"
          tree
  job_2:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: "echo Job: ${{github.job}} teste ${{vars.ENV_VAR_1}}"
      - run: echo "Little big things 🚀" >> $GITHUB_STEP_SUMMARY
  job_3:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: "echo Job: last parallel ${{github.job}}"
