name: My First Workflow

on: 
  push:
    branches: 
      -main
  workflow_dispatch:

  schedule:
    - cron: '0 15-17 10 */3 *'

jobs: 
  MyFirsJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🤗 Hello World!"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in the repository
        run: |
          echo " The repository ${{github.respository}} contains the following files:"
          tree
